language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE travis_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
env:
- DATABASE_URL=postgres://postgres@localhost/travis_test
notifications:
  email: false
deploy:
  provider: heroku
  app: travis-test-penguins
  skip_cleanup: true
  api_key:
    secure: IqWURT2y0A7lGqsTAkqMDkSbrVGEMK9q9+XSeg0up3s1UoGTpIeZfH8yWiaBS9aIhIwskNnFPvhE3jOhIzjtPZ8h3rBqPpAdpS5rmAgys3HKjjYKPe2/68NOxgWeZlYNEGNzQ9DDans3qT3HDyVNmkhCDp7O0c3WxJ+EZ6Ji1CUmoKPEuEjCS0L2Bwe+qX34FpXrJ7/qFyAML82mD+ei3+v6Diy83dY23kIsZKd3vgiDWKvwUtkIzcaxYOrU1PKak3rvRjx3TBMOh9GzO2lyhZDCWPXjE8MatC2nxuK5h/X4i5h1ufN5jP1FuVQ3xuJGgspBoh8QwEUCfnzw3UdFMvvUksjETA4+CIcc8utngWtvM/mok8egR4q9rFv0osRa5HCISc0pRA1hoZeprDpBRTGdC7T6YF4M3car+nT+U3zuVhv9L1ypRG8aewcBTKZQOJGKywDgZe465M6hm1wIH1qTfkliWqFACBuiduGDThn4kBwWqOew3DFv8EdAIESPwlqcLQqwCeeyMzpjNTvpIChlIxakdZKh5UuASsYLhgQLf90b4SpAQ3/yMD62VV3DjlQr1bdXornQ3mUiyC1mUjT4KJo6ikh2buXg07B121JjECRdQvN8cCRIVxKfKg9tHZHxNsCql37i4qzQUWO0KGnrXR8RYjCkBjxmMcTKn0I=
