language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis_test;' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost/travis_test
notifications:
  email: false