language: node_js
node_js: '8'
services:
- postgresql
before_script:
- psql -c 'create database travis_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Z0GdJI+KQtw4YKEcTMH3VQC3OU3xjcXABftKxNAtHugv5rBpzqD/4l6S24kRPR3EBafb91/YbwOAcfNvKXvpEVpXyONLM0nyE5OMJqdN2e77s8w1Tm2NGwLxQm30Au+xSSHYxv0dldZsSMBZeC6pN4M0xvsgDooiQGg08IB4wlopWWn/FbxbIK0wInYZdiuZUn77wTYLoqcXC+Ltzv4fc64/oao0zemvkyM62/vHwqzGse3HoC+wm/PYytmgF//taKR9S/y1XUiNpqchuQqrBQ7oGJVIyk3yATXQkaJ5nRQs/Ma7xQ2Ppqlmvo/foBAf6JsLudsohGrl1bCIprWGnVepDI1RBivkZvHyBrzKwWIqBEJVNPwWOB31RQKgbhs7byeEB6TkIJSeMTBMpskxmLFJ7gt+rfOs2xuCUkwyF8S1kwaiTYjKs8Z7mQOJ5VFsIpEYUQdTb7Js9bhh/2L6ITs/qvF8T6iux4o1o+tER5vr3NLvkCSDWdq9uAUakb52+KG6lZEWF4d0TxMs4FOWrEfNSUkjjQQ2kfoZWuwRS9hlCYvVWHXN0EdXqy9up5vA76wGTbBh4AE1sbuBupj7kTYklKdVTaoQt5C7oy1b1wNvIHzLsZEDBcYLpxOYtSTuPp+u/aepwbQuPg4rfH8I9LPhQSZF0an0GG3Usjrv2T4=
